### ISSUE TITLE
vue hash模式微信分享#号问题

### ISSUE THREAD

**Issue by cyio** [cyio/bch123.org#8]
问题描述：
在微信中分享到朋友圈或好友时，分享出去的路由被破坏，打开分享的链接，路由中的“#”会被去掉并追加？fromTimeline之类的后缀参数，这就造成了分享出去的链接只能进入首页，无法正常跳转到其他路由。  

[解决vue hash模式微信分享#号问题 - CSDN博客](https://blog.csdn.net/gyq04551/article/details/79746764)

>2、微信分享接口不支持hash传递。

        带有hash的url分享朋友圈的时候，跳转信息中 不包含hash信息。例如：

        view/guide/home.php#share/service/detail/

        只能得到：

        view/guide/home.php

        建议：分享的时候不要带hash信息。如果一定要带附加信息，可以转为：

        view/guide/home.php?share/service/detail/。

**Comment by cyio** [comment]
abstract mode 支持全 JS(Node) 环境，url 不变化
hash mode 访问正常，但分享复制 url 会被截断
history mode 本来可以，但由于用了 github pages 404，在微信平台会跳向公益404页面

**Comment by cyio** [comment]
[微信分享 总结（SPA/history模式） · Issue #78 · yongheng2016/blog](https://github.com/yongheng2016/blog/issues/78)
自定义分享需要公众号设置安全域名

**Comment by cyio** [comment]
总结：
* 404 方式是 hack，有兼容问题，避免使用
* SPA 只能使用 hash mode，需要手动处理 URL 分享
  - 页面提供 url 复制或分享二维码生成
  - 建议用户使用常规浏览器
  - hash mode 微信内不可行，会被加参数干扰

**Comment by cyio** [comment]
分享突然正常了

**Comment by BenesX** [comment]
你好，我想问下，hash模式下，安卓/ios可不可以在入口那里获取一次签名，然后再需要分享的页面用老的签名，要初始化wx.config
